services:
  react-portfolio14:
    build:
      context: .
      dockerfile: react-portfolio.dockerfile
    ports:
      - "3014:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - VITE_PORT=3000