# Install dependencies
FROM node:18-alpine

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .

ARG NEXT_VIRTUALGUIGO_CONFIG_ID
ARG NEXT_MIGRATIONDYNAMICS_CONFIG_ID
ARG NEXT_GWR_CONFIG_ID

ENV NEXT_VIRTUALGUIGO_CONFIG_ID=$NEXT_VIRTUALGUIGO_CONFIG_ID
ENV NEXT_MIGRATIONDYNAMICS_CONFIG_ID=$NEXT_MIGRATIONDYNAMICS_CONFIG_ID
ENV NEXT_GWR_CONFIG_ID=$NEXT_GWR_CONFIG_ID

RUN npm run build

EXPOSE 3000

CMD ["npm", "start"]


