# Install dependencies
FROM node:18-alpine

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .

ARG NEXT_PUBLIC_VIRTUALGUIGO_CONFIG_ID
ARG NEXT_PUBLIC_MIGRATIONDYNAMICS_CONFIG_ID
ARG NEXT_PUBLIC_GWR_CONFIG_ID

ENV NEXT_PUBLIC_VIRTUALGUIGO_CONFIG_ID=$NEXT_PUBLIC_VIRTUALGUIGO_CONFIG_ID
ENV NEXT_PUBLIC_MIGRATIONDYNAMICS_CONFIG_ID=$NEXT_PUBLIC_MIGRATIONDYNAMICS_CONFIG_ID
ENV NEXT_PUBLIC_GWR_CONFIG_ID=$NEXT_PUBLIC_GWR_CONFIG_ID

RUN npm run build

EXPOSE 3000

CMD ["npm", "start"]


