version: '3.7'

services:
  grafana:
    build:
      context: .
      dockerfile: grafana.dockerfile
    ports:
      - "3003:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_INSTALL_PLUGINS=grafana-piechart-panel,grafana-worldmap-panel

volumes:
  grafana-storage:
