version: '3.8'

services:
  fastapi:
    build:
      context: .
      dockerfile: fastapi.dockerfile
    ports:
      - "8081:8080"
    environment:
      - NODE_ENV=development
      - GOOGLE_APPLICATION_CREDENTIALS=/app/my-gcp-key.json
    volumes:
      - ../terraform/hub/terraform-sa-key.json:/app/my-gcp-key.json:ro
    