apiVersion: 1

datasources:
  - name: Google Cloud Monitoring
    type: stackdriver
    access: proxy
    jsonData:
      tokenUri: https://oauth2.googleapis.com/token
      clientEmail: stackdriver@myproject.iam.gserviceaccount.com
      authenticationType: jwt
      defaultProject: personalhub14
    secureJsonData:
      privateKey: |
        -----BEGIN PRIVATE KEY-----

        -----END PRIVATE KEY-----


